SAMPLE_RATE = 16000
FRAME_DURATION = 0.02
FRAME_SIZE = int(SAMPLE_RATE * FRAME_DURATION)

QUEUE_MAXSIZE = 100

SOURCE_LANG = "hi"
TARGET_LANG = "te"

START_THRESHOLD = 0.02
STOP_THRESHOLD = 0.01
SILENCE_DURATION = 0.8
MAX_SPEECH_DURATION = 8.0
MIN_SPEECH_DURATION = 0.8

ASR_MODEL_SIZE = "small"
DEVICE = "cuda"
COMPUTE_TYPE = "float16"