import time

state = {
    "energy": 0.0,
    "frames": 0,
    "speech_active": False,
    "start_time": time.time(),
    "offline_mode": None,
    "asr_status": "loading",
    "trans_status": "loading",
    "tts_status": "idle",
    "partial_transcript": "",
    "final_transcript": "",
    "asr_latency_ms": 0,
    "partial_translation": "",
    "final_translation": "",
    "trans_latency_ms": 0,
    "tts_latency_ms": 0,
    "e2e_latency_ms": 0,
    "trans_backend": "NLLB-200-600M",
    "total_words_asr": 0,
    "total_words_trans": 0,
    "speech_onset_time": None,
    "last_audio_duration": 0.0,
    "rtf": 0.00,
}
